---
title: "Global Dashboard"
author: "pandjibagas"
date: "7/31/2021"
output: html_document
---

# Prepare Data

```{r}
library(readxl)
library(dplyr)
library(ggplot2)
library(tidyr)
library(tidyverse)
library(hrbrthemes)
library(plotly)
library(viridis)
library(lubridate)
library(ggiraph)
library(glue)


olympic_athlete <- read.csv("athlete_events.csv") #main data
olympic_country <- read.csv("country_definitions.csv") #supporting data
athlete_def <- read.csv("athlete_events_data_dictionary.csv") #definition each coloumn from athlete_events.csv
country_def <-  read.csv("country_definitions_data_dictionary.csv") #definition each coloumn from country_definiitons.csv

olympic <- merge(olympic_athlete, olympic_country, by.x = "NOC", by.y = "NOC", all.x = T)
olympic_raw <- cbind(olympic)

olympic[,c("Sex","Team","NOC","Games","Season","City","Sport","Medal","Event","region")] <-
  lapply(olympic[,c("Sex","Team","NOC","Games","Season","City","Sport","Medal","Event","region")], as.factor)


olympic <- olympic[!is.na(olympic$Age),]
olympic <- olympic[!is.na(olympic$Height),]
olympic <- olympic[!is.na(olympic$Weight),]
olympic <- olympic[!is.na(olympic$region),]

no_medal <- olympic$Medal
no_medal <- as.character(no_medal)
no_medal[is.na(no_medal)] <- "No_Medal"
no_medal <- as.factor(no_medal)
olympic$Medal <- no_medal

olympic$notes <- NULL

olympic <- olympic %>%
  mutate(BMI = Weight/(Height/100)^2) %>%
  mutate_at(vars(BMI), funs(round(., 2)))

olympic <- olympic %>%
  mutate(BMI_category = case_when(BMI < 18.5 ~ "Underweight",
                                  BMI <= 24.9 ~ "Normal",
                                  BMI <= 29.9 ~ "Overweight",
                                  BMI <= 39.9 ~ "Obese",
                                  BMI >39.9 ~ "Morbidly Obese"))

olympic <- olympic %>%
  pivot_wider(
    names_from = Medal,
    values_from = Medal,
    values_fn = length,
    values_fill = 0) %>%
  mutate(Total_Medal = Bronze + Silver + Gold)

olympic$No_Medal <- NULL

olympic_raw <- olympic_raw %>%
  pivot_wider(
    names_from = Medal,
    values_from = Medal,
    values_fn = length,
    values_fill = 0) %>%
  mutate(Total_Medal = Bronze + Silver + Gold)

olympic_raw$No_Medal <- NULL
olympic_raw$"NA" <- NULL
olympic_raw$notes <- NULL



```

# Plot
```{r}
olympic_history_M <- olympic %>%
  filter(region == "USA", Sport == "Athletics", Sex == "M") %>%
  group_by(Year, ID) %>%
  summarise(BMI = mean(BMI))  %>%
  mutate(BMI_cat = case_when(BMI < 18.5 ~ "Underweight",
                                  BMI <= 24.9 ~ "Normal",
                                  BMI <= 29.9 ~ "Overweight",
                                  BMI <= 39.9 ~ "Obese",
                                  BMI >39.9 ~ "Morbidly Obese")) %>%
            
  ggplot(mapping = aes(y = BMI , x = as.factor(Year))) +
  geom_jitter(aes(col = BMI_cat), size = 1.5) +
  geom_boxplot(fill = "Gray", alpha = 0.3) +
  labs(title = "Olympians BMI by Year",
       subtitle = "Male Athlete",
       y = "BMI", x ="Year",
       col = "BMI Category")

olympic_history_M

```

```{r}
olympic_history_F <- olympic %>%
  filter(region == "USA", Sport == "Athletics", Sex == "F") %>%
  group_by(Year, ID) %>%
  summarise(BMI = mean(BMI))  %>%
  mutate(BMI_cat = case_when(BMI < 18.5 ~ "Underweight",
                                  BMI <= 24.9 ~ "Normal",
                                  BMI <= 29.9 ~ "Overweight",
                                  BMI <= 39.9 ~ "Obese",
                                  BMI >39.9 ~ "Morbidly Obese")) %>%
            
  ggplot(mapping = aes(y = BMI , x = as.factor(Year))) +
  geom_jitter(aes(col = BMI_cat), size = 1.5) +
  geom_boxplot(fill = "Gray", alpha = 0.3) +
  labs(title = "Olympians BMI by Year",
       subtitle = "Female Athlete",
       y = "BMI", x ="Year",
       col = "BMI Category") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(fill = "white"))

olympic_history_F

```

```{r}

olympians_freq <- olympic_raw %>%
  filter(region == "Indonesia", Sport == "Athletics") %>%
  group_by(ID) %>%
  summarise(Olympians = n_distinct(ID)) %>%
  count()

olympians_freq$n

```

```{r}

olympians_avg_BMI <- olympic %>%
  filter(region == "USA", Sport == "Athletics") %>%
  group_by(ID) %>%
  summarise(avg_BMI = mean(BMI))
  
olympians_avg_BMI <- mean(olympians_avg_BMI$avg_BMI)

olympians_avg_BMI

olympians_avg_BMI_cat <- if (olympians_avg_BMI < 18.5){
  print("Underweight")
} else if (olympians_avg_BMI <= 24.9){
    print("Normal")
} else if (olympians_avg_BMI <= 29.9){
  print("Overweight")
} else if (olympians_avg_BMI <= 39.9){
    print("Obese")
} else {
    print("Morbidly Obese")
  }
  
```

```{r}

olympians_medal <- olympic %>%
  filter(region == "USA", Sport == "Athletics") %>%
  select(Bronze, Silver, Gold) %>%
  pivot_longer(cols = c(Bronze,Silver,Gold)) %>%
  group_by(name) %>%
  summarise(Freq = sum(value))

olympians_total_medal <- sum(olympians_medal$Freq)

olympians_total_medal


```




```{r}

olympians_medal <- olympic %>%
  filter(region == "USA", Sport == "Athletics") %>%
  select(Bronze, Silver, Gold) %>%
  pivot_longer(cols = c(Bronze,Silver,Gold)) %>%
  group_by(name) %>%
  summarise(Freq = sum(value))
  
olympians_medal
    
medal_perc <- olympians_medal$Freq / sum(olympians_medal$Freq)

# Compute the cumulative percentages (top of each rectangle)
ymax <- cumsum(medal_perc)

# Compute the bottom of each rectangle
ymin <- c(0, head(ymax, n=-1))

# Compute label position
labelPosition <- (ymax + ymin) / 2

# Compute a good label
labelData <- paste0(olympians_medal$name, "\n value: ", olympians_medal$Freq)

# Make the plot
ggplot(olympians_medal, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=name)) +
  geom_rect() +
  #geom_label( x=3.5, aes(y=labelPosition, label=labelData), size=4) +
  scale_fill_manual(values=c("#cd7f32",
                             "#C0C0C0",
                             "#FFD700")) +
  coord_polar(theta="y") +
  xlim(c(2, 4)) +
  labs(fill = "Medal") +
  theme_void() +
  theme(legend.position = "bottom")


```

```{r}
olympians_BMI_cat <- olympic %>%
  pivot_wider(
    names_from = BMI_category,
    values_from = BMI_category,
    values_fn = length,
    values_fill = 0)

olympians_BMI_cat <- olympians_BMI_cat %>%
  filter(region == "Indonesia", Sport == "Athletics") %>%
  select("Underweight", "Normal", "Overweight", "Obese", "Morbidly Obese") %>%
  pivot_longer(cols = c("Underweight"| "Normal" | "Overweight" | "Obese" | "Morbidly Obese")) %>%
  group_by(name) %>%
  summarise(Freq = sum(value))

olympians_BMI_cat

BMI_perc <- olympians_BMI_cat$Freq / sum(olympians_BMI_cat$Freq)

# Compute the cumulative percentages (top of each rectangle)
ymax <- cumsum(BMI_perc)

# Compute the bottom of each rectangle
ymin <- c(0, head(ymax, n=-1))

# Compute label position
labelPosition <- (ymax + ymin) / 2

# Compute a good label
labelData <- paste0(olympians_BMI_cat$Freq)

# Make the plot
ggplot(olympians_BMI_cat, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=name)) +
  geom_rect() +
  #geom_label( x=3.8, aes(y=labelPosition, label=labelData), size=3) +
  scale_fill_brewer(palette=8) +
  coord_polar(theta="y") +
  xlim(c(2, 4)) +
  labs(fill = "BMI Category") +
  theme_void() +
  theme(legend.position = "bottom")
```

```{r}
olympians_gender <- olympic_raw %>%
  filter(region == "USA", Sport == "Athletics") %>%
  group_by(Sex) %>%
  summarise(Freq = n_distinct(ID))

olympians_gender

BMI_perc <- olympians_gender$Freq / sum(olympians_gender$Freq)

# Compute the cumulative percentages (top of each rectangle)
ymax <- cumsum(BMI_perc)

# Compute the bottom of each rectangle
ymin <- c(0, head(ymax, n=-1))

# Compute label position
labelPosition <- (ymax + ymin) / 2

# Compute a good label
labelData <- paste0(olympians_gender$Freq)

# Make the plot
ggplot(olympians_gender, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=Sex)) +
  geom_rect_interactive() +
  geom_label( x=3.5, aes(y=labelPosition, label=labelData), size=4) +
  scale_fill_brewer(palette=14) +
  coord_polar(theta="y") +
  xlim(c(2, 4)) +
  labs(fill = "Gender") +
  theme_void() +
  theme(legend.position = "bottom")
```













```{r}

olympic_time <- olympic_raw %>%
  filter(region == "USA", Sport == "Athletics") %>%
  group_by(Year) %>%
  summarise(Olympians = n_distinct(ID))  %>%
  mutate(text = glue("Year   : {Year}
                      Gender : {Olympians}")) %>%
  
  ggplot(mapping = aes(x = Year , y = Olympians)) +
  geom_area(alpha=0.3 , size=.5, colour="#14b89f", fill="#18dec0") +
  geom_point(col = "#11a68f") +
  scale_x_continuous(breaks = seq(1896,2016,8)) +
  labs(y = "Participants", x ="Year") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(fill = "white"))
 

ggplotly(olympic_time, tooltip = "text")

```



```{r}


BMI_calculator <- olympic$Weight / sqrt(olympic$Height/100)
BMI_calculator <- 71/(171/100)^2
BMI_category <- if (BMI_calculator < 18.5){
            print("Underweight")
        } else if (BMI_calculator <= 24.9){
            print("Normal")
        } else if (BMI_calculator <= 29.9){
            print("Overweight")
        } else if (BMI_calculator <= 39.9){
            print("Obese")
        } else {
            print("Morbidly Obese")
        }

BMI_category
```

```{r}
olympic_gender <- olympic_raw %>%
  filter(Season %in% "Summer", region %in% "USA", Sport %in% "Athletics") %>%
  group_by(Year, Sex) %>%
  summarise(Olympians = n_distinct(ID))  %>%
  pivot_wider(
    names_from = Sex,
    values_from = Olympians,
    values_fill = 0) %>%
  setNames(c("Year","Male","Female")) %>%
  mutate("Total" = Male + Female) %>%
  pivot_longer(cols =c("Total","Male","Female")) %>%
  mutate(name = factor(name, levels = c("Total","Male","Female"))) %>%
  mutate(text = glue("Year   : {Year}
                      Gender : {name}
                      Amount : {value}")) %>%
  
  ggplot(aes(x = Year , y = value, col = name, fill = name)) +
  geom_area(position = position_dodge(), alpha = 0.6) +
  geom_point() +
  geom_line() +
  scale_fill_manual(values = c("#3700B3","#03dac4","#92e9dc")) +
  scale_color_manual(values = c("#3700B3","#03dac4","#92e9dc")) +
  scale_x_continuous(breaks = seq(1896,2016,8)) +
  theme(legend.position = "bottom",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white"),
        axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        axis.ticks.y=element_blank())
  
    
  ggplotly(olympic_gender)

```
```{r}
olympic_gender <- olympic_raw %>%
  filter(Season %in% "Winter") %>%
  group_by(Year, Sex) %>%
  summarise(Olympians = n_distinct(ID))  %>%
  pivot_wider(
    names_from = Sex,
    values_from = Olympians,
    values_fill = 0) %>%
  setNames(c("Year","Male","Female")) %>%
  mutate("Total" = Male + Female) %>%
  pivot_longer(cols =c("Total","Male","Female")) %>%
  mutate(name = factor(name, levels = c("Total","Male","Female"))) %>%
  mutate(text = glue("Year   : {Year}
                      Gender : {name}
                      Amount : {value}")) %>%
  
  ggplot(aes(x = Year , y = value, col = name, fill = name)) +
  geom_area(position = position_dodge(), alpha = 0.6) +
  geom_point(aes(text = text)) +
  geom_line() +
  scale_fill_manual(values = c("#3700B3","#03dac4","#92e9dc")) +
  scale_color_manual(values = c("#3700B3","#03dac4","#92e9dc")) +
  scale_x_continuous(breaks = seq(1896,2016,8)) +
  theme(legend.position = "bottom",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white"),
        axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        axis.ticks.y=element_blank())

ggplotly(olympic_gender, tooltip = "text")

```







```{r}
olympic %>%
  filter() %>%
  group_by(region) %>% 
  summarise(avg_age = mean(Age),
            avg_height = mean(Height),
            avg_weight = mean(Weight),
            avg_BMI = mean(BMI)) %>%
  mutate(BMI_cat_country = case_when(avg_BMI < 18.5 ~ "Underweight",
                                  avg_BMI <= 24.9 ~ "Normal",
                                  avg_BMI <= 29.9 ~ "Overweight",
                                  avg_BMI <= 39.9 ~ "Obese",
                                  avg_BMI >39.9 ~ "Morbidly Obese")) %>%
  arrange(-avg_BMI) %>%
  head(30) %>%
  ggplot(aes(y= reorder(region,avg_BMI), x = avg_BMI)) +
  geom_col(aes(fill = BMI_cat_country)) +
  scale_fill_brewer(palette= 14) +
  labs(x = "Country", y = "BMI")
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(fill = "white"))
  
  
```
```{r}


athlete_BMI <- olympic %>%
  filter(Season %in% "Summer", region %in% "USA") %>%
  group_by(ID, Name) %>% 
  summarise(avg_BMI = mean(BMI)) %>%
  mutate(BMI_cat_country = case_when(avg_BMI < 18.5 ~ "Underweight",
                                  avg_BMI <= 24.9 ~ "Normal",
                                  avg_BMI <= 29.9 ~ "Overweight",
                                  avg_BMI <= 39.9 ~ "Obese",
                                  avg_BMI >39.9 ~ "Morbidly Obese")) %>%
  mutate(BMI_cat_country = factor(BMI_cat_country, levels = c("Underweight","Normal","Overweight", "Obese", "Morbidly Obese"))) %>%
  mutate(text = glue("BMI : {avg_BMI}")) %>%
  
  arrange(-avg_BMI) %>%
  head(30) %>%
  ggplot(aes(y= reorder(Name,avg_BMI), x = avg_BMI)) +
  geom_col(aes(fill = BMI_cat_country, text = text)) +
  labs(title = "Olympians with Highest BMI",
        y = "",
        x ="BMI",
       fill = "BMI Category") +
  scale_fill_manual(values = c("#03dac4","#3700B3","#D1C4E9","#92e9dc","#00838F")) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(fill = "white"), plot.title = element_text(face = "bold"))
  
  ggplotly(athlete_BMI, tooltip = "text")
  
```

```{r}

medal_country <- olympic_raw %>%
  filter(Season %in% "Summer", region %in% "USA", Sport %in% "Athletics") %>%
  group_by(Year, region) %>%
  summarise(Bronze = sum(Bronze),
            Silver = sum(Silver),
            Gold = sum(Gold),
            Total_Medal = sum(Total_Medal)) %>%
  filter(Total_Medal == max(Total_Medal)) %>%
  select(region, Bronze, Silver, Gold) %>%
  pivot_longer(cols =c(Bronze,Silver, Gold)) %>%
  mutate(name = factor(name, levels = c("Gold","Silver","Bronze"))) %>%
  mutate(text = glue("Region : {region}
              Medal : {name}
              Amounts : {value}")) %>%
  

  ggplot(mapping = aes(y = value, x = Year, fill = name, text = text)) +
  geom_col(stacked = TRUE) +
  labs(title = "Country with Highest Medal by Year",
       y = "BMI", x ="Year",
       fill = "Medal") +
  scale_x_continuous(breaks = seq(1896,2016,8)) +
  scale_fill_manual(values = c("#3700B3","#03dac4","#92e9dc")) +
  theme(legend.position = "bottom",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white"),
        axis.text.y=element_blank(),
        axis.title.y=element_blank(),
        axis.ticks.y=element_blank())


ggplotly(medal_country, tooltip = "text")
```

```{r}
olympic_gender <- olympic_raw %>%
  filter(Season == "Winter") %>%
  group_by(Year, Sex) %>%
  summarise(Olympians = n_distinct(ID))  %>%
  pivot_wider(
    names_from = Sex,
    values_from = Olympians,
    values_fill = 0) %>%
  mutate(total_olympians = M + F) %>%
  pivot_longer(cols =c(M,F,total_olympians))
    
  
  olympic_gender <- ggplot(olympic_gender, mapping = aes(x = Year , y = value, col = name)) +
  geom_line() +
  geom_point() +
  #scale_x_date(date_labels = "%Y", date_minor_breaks = "2 year", limits = as.Date(c("1896-01-01","2016-01-01"))) +
  labs(y = "Participants", x ="Year", col = "Athlete Gender" ) +
  scale_color_brewer(palette= "Blues") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(fill = "white"))
 

 olympic_gender
```

```{r}
average_bmi <- olympic %>%
  filter(Season %in% "Winter") %>%
  group_by(Year) %>%
  summarise(Avg_BMI = mean(BMI)) %>%
  mutate_at(vars(Avg_BMI), funs(round(., 2))) %>%
  mutate(BMI_cat_country = case_when(Avg_BMI < 18.5 ~ "Underweight",
                                  Avg_BMI <= 24.9 ~ "Normal",
                                  Avg_BMI <= 29.9 ~ "Overweight",
                                  Avg_BMI <= 39.9 ~ "Obese",
                                  Avg_BMI >39.9 ~ "Morbidly Obese")) %>%
  mutate(text = glue("Year   : {Year}
                      BMI : {Avg_BMI}
                      Category : {BMI_cat_country}")) %>%
  
 ggplot(aes(x = Year, y = Avg_BMI)) +
  geom_area()

ggplotly(olympic_gender, tooltip = "text")
```
```{r}
olympic
```



```


